//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC301.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public int ClaveP { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<int> Existencias { get; set; }
        public Nullable<int> IdP { get; set; }
    
        public virtual proveedores proveedores { get; set; }
    }
}
