//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC301.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas
    {
        public int IdVenta { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public Nullable<int> ClaveP { get; set; }
        public Nullable<int> Iva { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual vendedor vendedor { get; set; }
    }
}
